package CommonlyUsedDesignPatterns.StructuralDesignPatterns.DecoratorDesignPattern.Decorator;

import CommonlyUsedDesignPatterns.StructuralDesignPatterns.DecoratorDesignPattern.Pizza.BasePizza;

public interface ToppingsDecorator extends BasePizza {
}
